name: Sheldon Morey
favicon: null
layout_spectrum: 0.18658480956219137
typography_spectrum: 0.29105044901371
title: Sheldon Morey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.61329111084342
  lightness: 0.5410005862358958
  saturation: 0.40532594453543425
  rhythmicContrast: 0.05426137917675078
purpose: []
