name: Sheldon Morey
favicon: null
layout_spectrum: 0.6810613959096372
typography_spectrum: 0.6984559984412044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#005099'
    - '#4788be'
    - '#af5c27'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6044484621379524
purpose: []
